[tox]
envlist = py39, py310, py311, py312
isolated_build = True

[testenv]
extras = test
commands = pytest --cov=pytorch_wavelets --cov-report=term {posargs}

[testenv:docs]
extras = docs
changedir = docs
commands = sphinx-build -b html . _build/html
